### PR TITLE
Allow custom "since" value

### PR DESCRIPTION
**Pull request by marob**

### CODE REVIEW

**Comment by soldair** [comment]
I'm curious about your use case. could you tell me a bit more about how this is helpful to you?

if you always want to start from latest and you dont care if you miss documents wouldn't you just use changes-stream itself?

**Comment by marob** [comment]
Say, you want to be notified of all future updates from the moment you start your script the first time (and not all modifications since 0).
If you stop your script and re-launch it later, you want to continue from the last revision when you stopped the script (so, I don't want to miss documents).

My first approach was to create the .sequence file with "now", but it stays with this value and when you restart your script il doesn't catch up.

For a complete usage example, see https://github.com/Smile-SA/npmjs-enterprise/blob/noCouchDb/lib/api.js#L121

**Comment by soldair** [comment]
would you consider changing this to be a config option called "now" with the logic being something like what you have in your code?

if(config.now && !seq) db.since = 'now'

**Comment by marob** [comment]
Is this better?

**Comment by soldair** [comment]
I would like to only check the configured now value if there is no saved sequence. Like it should only have an effect if you'really starting fresh. I'll make that change tonight and merge this in. 

This is how you are using it anyway and it makes it impossible to get stale versions of metadata stuck in a cache.

**Comment by marob** [comment]
OK, so you propose:
- if first start
  - if `now` is true: `since="now"`
  - else `since=0`
- else `since=value of the sequence file`

I'm OK with that.

**Comment by marob** [comment]
I've updated the PR

**Comment by soldair** [comment]
Looks good. I'll merge it when I get back to the computer.  The sequence is already loaded so we can remove the extra fs stuff. And just use seq.value

**Comment by marob** [comment]
You mean we could define `firstStart=(seq.value===0)`?

**Comment by soldair** [comment]
Yup

**Comment by marob** [comment]
That should do the trick!

**Comment by soldair** [comment]
Thanks! Sorry that was so tedious

**Comment by marob** [comment]
No problem, as long as the result is clean :)

**Comment by soldair** [comment]
landed in v1.1.0

**Pull request merged**
